FROM continuumio/miniconda3

LABEL name="sketchy"
LABEL version="0.5.0"
LABEL author="esteinig"

RUN apt-get update && apt-get install curl build-essential procps git -y

ENV SKETCHY_BRANCH=v0.5.0
ENV MASH_VERSION=2.2.2
ENV CONDA_DIR=/opt/conda
ENV SKETCHY_PATH=/sketchy

ENV PATH=/opt/conda/bin:/rust/.cargo/bin:$PATH
ENV CARGO_HOME=/rust/.cargo
ENV RUSTUP_HOME=/rust/.rustup

RUN conda install -c conda-forge -c bioconda -c esteinig --yes \
    pysam mash=$MASH_VERSION psutil drep checkm-genome mummer

RUN mkdir /rust && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

RUN git clone -b $SKETCHY_BRANCH --single-branch https://github.com/esteinig/sketchy.git
RUN pip install ./sketchy
RUN cd ./sketchy && cargo build && mv target/debug/sketchy /usr/local/bin