FROM esteinig/sketchy:latest

LABEL name="sketchy-dev"
LABEL version="latest"
LABEL author="esteinig"

COPY . /sketchy

RUN pip install /sketchy

# /data workdir for easy bindmounts
WORKDIR /data
CMD []
