{% set version = "0.5.0" %}

# conda build -c esteinig -c bioconda -c conda-forge .

package:
  name: sketchy
  version: {{ version }}

source:
  path: . # [linux]

build:
  number: 0

requirements:
  build:
      - {{ compiler('cxx') }}
  host:
      - python>=3.7
      - rust>=1.39
  run:
      - python>=3.7
      - rust>=1.39
      - mash=2.2
      - wget
      - nextflow
      - tqdm
      - colorama
      - pandas
      - click
      - pytest
      - seaborn
      - scipy
      - python-dateutil
      - numpy
      - pysam
      - psutil
      - matplotlib-base
      - deprecation
      - braceexpand
      - networkx
      - pyfastx
      - watchdog
test:
  imports:
    - sketchy
  commands:
    - sketchy --help
    - sketchy-rs -h

about:
  home: 'https://github.com/esteinig/sketchy'
  license: MIT
  license_file: LICENSE
  summary: 'Real-time db_lineage hashing and genotyping of bacterial pathogens'

